# Generated by Django 2.1 on 2019-06-03 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_finder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersratings',
            old_name='beverages',
            new_name='car',
        ),
        migrations.RenameField(
            model_name='usersratings',
            old_name='food',
            new_name='golf',
        ),
        migrations.RenameField(
            model_name='usersratings',
            old_name='low_budget',
            new_name='house',
        ),
        migrations.RenameField(
            model_name='usersratings',
            old_name='newness',
            new_name='morning',
        ),
    ]
