# Generated by Django 2.1 on 2019-06-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_finder', '0002_auto_20190603_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='businesses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=0, max_length=50)),
                ('category', models.CharField(default=0, max_length=25)),
                ('address', models.CharField(default=0, max_length=100)),
                ('phoneNumber', models.CharField(default=0, max_length=50)),
                ('link', models.URLField(default=0)),
                ('description', models.CharField(default=0, max_length=500)),
            ],
        ),
    ]
