# Generated by Django 2.1 on 2019-06-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_finder', '0004_auto_20190604_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesses',
            name='car',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='businesses',
            name='general',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='businesses',
            name='golf',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='businesses',
            name='house',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='businesses',
            name='morning',
            field=models.IntegerField(default=0),
        ),
    ]
